export { default as CityHubPage } from './ui/CityHubPage'
export { default as RegionHubPage } from './ui/RegionHubPage'
export { getCityData, getRegionData } from './data'
export { getAllCityParams, getAllRegionParams, getCityWithRegion, getRegionBySlug, REGIONS } from './config/registry'
export { SEGMENT_CARDS } from './config/segments'
export type { CityHubData, RegionHubData, CityRouteData, CityFaqData, CooperationData, SegmentCardData } from './types'
