import type { ArticleEntry } from '../types'

export const ARTICLES: ArticleEntry[] = [
  // ===== Сегмент 1: Корпоративное такси (10 статей) =====
  {
    slug: 'kak-organizovat-korporativnye-mezhgorodnie-poezdki',
    segment: 'korporativnoe-taksi',
    format: 'guide',
    title: 'Как организовать корпоративные межгородние поездки',
    description: 'Пошаговое руководство по организации межгородних поездок для сотрудников. Выбор перевозчика, оформление документов, контроль расходов.',
    keywords: 'корпоративные межгородние поездки, организация командировок, корпоративный трансфер',
    readingTime: 12,
  },
  {
    slug: 'chek-list-vybora-transportnoj-kompanii-dlya-biznesa',
    segment: 'korporativnoe-taksi',
    format: 'checklist',
    title: 'Чек-лист выбора транспортной компании для бизнеса',
    description: 'Проверочный список из 15 критериев для выбора надёжного перевозчика. Договор, страховка, автопарк, отзывы.',
    keywords: 'выбор транспортной компании, чек-лист перевозчик, транспортная компания для бизнеса',
    readingTime: 8,
  },
  {
    slug: 'sravnenie-korporativnogo-taksi-i-agregatorov',
    segment: 'korporativnoe-taksi',
    format: 'comparison',
    title: 'Сравнение корпоративного такси и агрегаторов',
    description: 'Подробное сравнение корпоративного такси и агрегаторов по цене, сервису, документам и надёжности для бизнеса.',
    keywords: 'корпоративное такси vs агрегаторы, сравнение такси для бизнеса, Яндекс такси для юрлиц',
    readingTime: 10,
  },
  {
    slug: 'kejs-kak-it-kompaniya-sokratila-raskhody-na-komandirovki',
    segment: 'korporativnoe-taksi',
    format: 'case-study',
    title: 'Кейс: как IT-компания сократила расходы на командировки на 35%',
    description: 'Реальный кейс оптимизации транспортных расходов IT-компании с 200 сотрудниками при переходе на корпоративное такси.',
    keywords: 'кейс корпоративное такси, оптимизация расходов командировки, экономия на такси',
    readingTime: 9,
  },
  {
    slug: 'stoimost-korporativnogo-taksi-mezhgorod-obzor-cen',
    segment: 'korporativnoe-taksi',
    format: 'price-review',
    title: 'Стоимость корпоративного такси межгород: обзор цен 2025',
    description: 'Актуальный обзор цен на корпоративное такси межгород. Сравнение тарифов, от чего зависит цена, как сэкономить.',
    keywords: 'стоимость корпоративного такси, цены такси межгород, тарифы корпоративное такси',
    readingTime: 11,
  },
  {
    slug: 'kak-nastroit-edo-dlya-korporativnyh-poezdok',
    segment: 'korporativnoe-taksi',
    format: 'guide',
    title: 'Как настроить ЭДО для корпоративных поездок',
    description: 'Руководство по настройке электронного документооборота с транспортной компанией. СБИС, Контур.Диадок, 1С — пошаговая инструкция.',
    keywords: 'ЭДО корпоративные поездки, электронный документооборот такси, настройка ЭДО перевозки',
    readingTime: 10,
  },
  {
    slug: 'chek-list-dokumentov-dlya-dogovora-na-korporativnye-perevozki',
    segment: 'korporativnoe-taksi',
    format: 'checklist',
    title: 'Чек-лист документов для договора на корпоративные перевозки',
    description: 'Полный перечень документов для заключения договора на корпоративные перевозки. Что подготовить заказчику и перевозчику.',
    keywords: 'документы договор перевозки, чек-лист документов такси, договор корпоративные перевозки',
    readingTime: 7,
  },
  {
    slug: 'korporativnoe-taksi-vs-arenda-avto-s-voditelem',
    segment: 'korporativnoe-taksi',
    format: 'comparison',
    title: 'Корпоративное такси vs аренда авто с водителем: что выгоднее',
    description: 'Сравниваем два варианта корпоративного транспорта. Стоимость, удобство, гибкость, документы — что выбрать для бизнеса.',
    keywords: 'корпоративное такси или аренда, аренда авто с водителем, сравнение корпоративный транспорт',
    readingTime: 9,
  },
  {
    slug: 'kejs-logistika-komandirovok-stroitelnoj-kompanii',
    segment: 'korporativnoe-taksi',
    format: 'case-study',
    title: 'Кейс: логистика командировок строительной компании',
    description: 'Как строительная компания с объектами в 12 регионах наладила систему межгородних перевозок сотрудников.',
    keywords: 'кейс строительная компания, логистика командировок, перевозка сотрудников строительство',
    readingTime: 10,
  },
  {
    slug: 'skolko-stoit-korporativnyj-transfer-moskva-spb',
    segment: 'korporativnoe-taksi',
    format: 'price-review',
    title: 'Сколько стоит корпоративный трансфер Москва — Санкт-Петербург',
    description: 'Подробный разбор цен на корпоративный трансфер между Москвой и Петербургом. Классы авто, время в пути, что включено в стоимость.',
    keywords: 'трансфер Москва Петербург цена, корпоративный трансфер Москва СПб, стоимость такси Москва Петербург',
    readingTime: 8,
  },

  // ===== Сегмент 2: Трансфер для мероприятий (10 статей) =====
  {
    slug: 'kak-organizovat-transfer-dlya-konferencii',
    segment: 'transfer-meropriyatiy',
    format: 'guide',
    title: 'Как организовать трансфер для конференции',
    description: 'Пошаговое руководство по организации трансфера участников конференции. Планирование маршрутов, выбор транспорта, координация.',
    keywords: 'трансфер конференция, организация трансфера мероприятие, перевозка участников конференции',
    readingTime: 12,
  },
  {
    slug: 'chek-list-transportnoj-logistiki-meropriyatiya',
    segment: 'transfer-meropriyatiy',
    format: 'checklist',
    title: 'Чек-лист транспортной логистики мероприятия',
    description: 'Проверочный список для организаторов: от планирования маршрутов до обратного трансфера. 20 пунктов без которых не обойтись.',
    keywords: 'чек-лист логистика мероприятия, транспорт для мероприятия, организация трансфера',
    readingTime: 8,
  },
  {
    slug: 'sravnenie-transfer-servisy-dlya-meropriyatiy',
    segment: 'transfer-meropriyatiy',
    format: 'comparison',
    title: 'Сравнение трансфер-сервисов для мероприятий',
    description: 'Сравниваем типы трансфер-сервисов для мероприятий: агрегаторы, чартеры, корпоративное такси. Плюсы и минусы каждого.',
    keywords: 'трансфер сервис мероприятия, сравнение трансфер компаний, перевозка на мероприятие',
    readingTime: 10,
  },
  {
    slug: 'kejs-transfer-dlya-korporativa-na-500-chelovek',
    segment: 'transfer-meropriyatiy',
    format: 'case-study',
    title: 'Кейс: трансфер для корпоратива на 500 человек',
    description: 'Как мы организовали трансфер 500 сотрудников на загородный корпоратив. Маршруты, тайминг, координация в реальном времени.',
    keywords: 'кейс трансфер корпоратив, перевозка сотрудников мероприятие, логистика корпоратива',
    readingTime: 9,
  },
  {
    slug: 'stoimost-transfera-dlya-meropriyatij-obzor-cen',
    segment: 'transfer-meropriyatiy',
    format: 'price-review',
    title: 'Стоимость трансфера для мероприятий: обзор цен',
    description: 'Сколько стоит трансфер для конференций, форумов и корпоративов. Тарифы на минивэны, автобусы, представительский класс.',
    keywords: 'стоимость трансфера мероприятие, цена перевозки конференция, тарифы трансфер мероприятия',
    readingTime: 11,
  },
  {
    slug: 'kak-organizovat-transfer-gostej-na-svadbu-za-gorodom',
    segment: 'transfer-meropriyatiy',
    format: 'guide',
    title: 'Как организовать трансфер гостей на свадьбу за городом',
    description: 'Полное руководство по организации трансфера свадебных гостей. Маршруты, расписание, выбор транспорта, бюджет.',
    keywords: 'трансфер свадьба за городом, перевозка гостей свадьба, трансфер свадьба организация',
    readingTime: 10,
  },
  {
    slug: 'chek-list-transfera-dlya-delovogo-foruma',
    segment: 'transfer-meropriyatiy',
    format: 'checklist',
    title: 'Чек-лист трансфера для делового форума',
    description: 'Полный чек-лист организации трансфера для делового форума: VIP-гости, спикеры, массовый подвоз участников.',
    keywords: 'чек-лист трансфер форум, логистика деловой форум, организация трансфера форум',
    readingTime: 7,
  },
  {
    slug: 'miniveny-vs-avtobusy-dlya-korporativnyh-meropriyatij',
    segment: 'transfer-meropriyatiy',
    format: 'comparison',
    title: 'Минивэны vs автобусы для корпоративных мероприятий',
    description: 'Когда лучше заказать минивэны, а когда автобус? Сравнение по вместимости, комфорту, стоимости и гибкости маршрутов.',
    keywords: 'минивэн или автобус мероприятие, выбор транспорта корпоратив, сравнение минивэн автобус',
    readingTime: 9,
  },
  {
    slug: 'kejs-logistika-mezhdunarodnogo-foruma-v-sochi',
    segment: 'transfer-meropriyatiy',
    format: 'case-study',
    title: 'Кейс: логистика международного форума в Сочи',
    description: 'Организация трансфера 2000 участников международного форума из аэропорта Сочи в 5 отелей. Решение в деталях.',
    keywords: 'кейс трансфер форум Сочи, логистика форума, перевозка участников форум',
    readingTime: 11,
  },
  {
    slug: 'byudzhet-transfera-dlya-konferencii-skolko-zakladyvat',
    segment: 'transfer-meropriyatiy',
    format: 'price-review',
    title: 'Бюджет трансфера для конференции: сколько закладывать',
    description: 'Как рассчитать транспортный бюджет мероприятия. Формулы расчёта, типичные статьи расходов, способы оптимизации.',
    keywords: 'бюджет трансфер конференция, расчёт стоимости трансфера, транспортный бюджет мероприятие',
    readingTime: 10,
  },

  // ===== Сегмент 3: Перевозка вахтовых рабочих (10 статей) =====
  {
    slug: 'kak-organizovat-vakhtovuyu-perevozku-rabochih',
    segment: 'vakhtovye-perevozki',
    format: 'guide',
    title: 'Как организовать вахтовую перевозку рабочих',
    description: 'Руководство по организации перевозки вахтовых бригад. Маршруты, графики, требования безопасности, документы.',
    keywords: 'вахтовая перевозка рабочих, организация вахтового трансфера, перевозка бригад',
    readingTime: 13,
  },
  {
    slug: 'chek-list-bezopasnosti-perevozki-vakhtovyh-brigad',
    segment: 'vakhtovye-perevozki',
    format: 'checklist',
    title: 'Чек-лист безопасности перевозки вахтовых бригад',
    description: 'Требования безопасности при перевозке вахтовых рабочих. Нормы, документы, проверка транспорта — 18 обязательных пунктов.',
    keywords: 'безопасность перевозка вахта, чек-лист перевозка рабочих, требования перевозка бригад',
    readingTime: 8,
  },
  {
    slug: 'vakhtovyj-avtobus-vs-taksi-mezhgorod-sravnenie',
    segment: 'vakhtovye-perevozki',
    format: 'comparison',
    title: 'Вахтовый автобус vs такси межгород: сравнение',
    description: 'Сравнение вахтового автобуса и междугороднего такси для перевозки бригад. Стоимость, комфорт, гибкость, скорость.',
    keywords: 'вахтовый автобус или такси, сравнение перевозка вахта, такси для вахтовиков',
    readingTime: 9,
  },
  {
    slug: 'kejs-perevozka-burovyh-brigad-na-mestorozhdeniya-yugry',
    segment: 'vakhtovye-perevozki',
    format: 'case-study',
    title: 'Кейс: перевозка буровых бригад на месторождения Югры',
    description: 'Как нефтесервисная компания организовала регулярную перевозку 120 рабочих на месторождения Ханты-Мансийского АО.',
    keywords: 'кейс перевозка вахта, буровые бригады перевозка, трансфер месторождение Югра',
    readingTime: 10,
  },
  {
    slug: 'stoimost-perevozki-vakhtovyh-rabochih-obzor-cen',
    segment: 'vakhtovye-perevozki',
    format: 'price-review',
    title: 'Стоимость перевозки вахтовых рабочих: обзор цен',
    description: 'Актуальные тарифы на перевозку вахтовых бригад. Легковые, минивэны, автобусы — от чего зависит цена.',
    keywords: 'стоимость перевозка вахта, цены перевозка рабочих, тарифы вахтовый трансфер',
    readingTime: 11,
  },
  {
    slug: 'kak-sokratit-prostoi-pri-smene-vakhtovyh-brigad',
    segment: 'vakhtovye-perevozki',
    format: 'guide',
    title: 'Как сократить простои при смене вахтовых бригад',
    description: 'Методы оптимизации логистики смены вахт. Планирование маршрутов, синхронизация графиков, резервный транспорт.',
    keywords: 'простои смена вахты, оптимизация вахтовой логистики, ротация вахтовых бригад',
    readingTime: 10,
  },
  {
    slug: 'chek-list-dokumentov-dlya-perevozki-vakhtovyh-rabochih',
    segment: 'vakhtovye-perevozki',
    format: 'checklist',
    title: 'Чек-лист документов для перевозки вахтовых рабочих',
    description: 'Какие документы нужны перевозчику и заказчику для организации вахтовых перевозок. Нормативные требования и шаблоны.',
    keywords: 'документы перевозка вахта, чек-лист документов вахтовиков, оформление перевозки рабочих',
    readingTime: 7,
  },
  {
    slug: 'lichnoe-taksi-vs-gruppovoj-transfer-dlya-vakhtovikov',
    segment: 'vakhtovye-perevozki',
    format: 'comparison',
    title: 'Личное такси vs групповой трансфер для вахтовиков',
    description: 'Что выгоднее: индивидуальный трансфер или групповая перевозка вахтовых рабочих? Считаем стоимость на человека.',
    keywords: 'личное такси вахтовики, групповой трансфер вахта, сравнение перевозка вахтовых',
    readingTime: 9,
  },
  {
    slug: 'kejs-dostavka-stroitelnyh-brigad-na-obekty-v-arktike',
    segment: 'vakhtovye-perevozki',
    format: 'case-study',
    title: 'Кейс: доставка строительных бригад на объекты в Арктике',
    description: 'Организация перевозки строительных бригад на арктические объекты. Логистика в экстремальных условиях.',
    keywords: 'кейс перевозка Арктика, строительные бригады Арктика, логистика вахта Север',
    readingTime: 11,
  },
  {
    slug: 'tarify-na-perevozku-brigad-kak-rasschitat-byudzhet',
    segment: 'vakhtovye-perevozki',
    format: 'price-review',
    title: 'Тарифы на перевозку бригад: как рассчитать бюджет',
    description: 'Формулы расчёта бюджета на вахтовые перевозки. Фиксированные и сдельные тарифы, скрытые расходы, оптимизация.',
    keywords: 'тарифы перевозка бригад, расчёт бюджета вахта, стоимость вахтовых перевозок',
    readingTime: 10,
  },

  // ===== Сегмент 4: Медицинский трансфер (10 статей) =====
  {
    slug: 'kak-organizovat-medicinskij-transfer-pacientov',
    segment: 'medicinskij-transfer',
    format: 'guide',
    title: 'Как организовать медицинский трансфер пациентов',
    description: 'Руководство по организации межгороднего трансфера пациентов. Выбор транспорта, сопровождение, документы, страховка.',
    keywords: 'медицинский трансфер пациентов, перевозка пациентов межгород, организация медтрансфера',
    readingTime: 13,
  },
  {
    slug: 'chek-list-perevozki-pacienta-mezhgorod',
    segment: 'medicinskij-transfer',
    format: 'checklist',
    title: 'Чек-лист перевозки пациента межгород',
    description: 'Что проверить перед межгородней перевозкой пациента. Медицинские документы, подготовка, комфорт, связь с клиникой.',
    keywords: 'чек-лист перевозка пациент, подготовка медтрансфер, перевозка пациент межгород',
    readingTime: 8,
  },
  {
    slug: 'sanitarnyj-transport-vs-komfortnoe-taksi-dlya-pacientov',
    segment: 'medicinskij-transfer',
    format: 'comparison',
    title: 'Санитарный транспорт vs комфортное такси для пациентов',
    description: 'Когда нужна санитарная машина, а когда достаточно комфортного такси? Сравнение по показаниям, стоимости, оснащению.',
    keywords: 'санитарный транспорт или такси, перевозка пациентов сравнение, медицинское такси',
    readingTime: 10,
  },
  {
    slug: 'kejs-perevozka-onkopacientov-na-lechenie-v-moskvu',
    segment: 'medicinskij-transfer',
    format: 'case-study',
    title: 'Кейс: перевозка онкопациентов на лечение в Москву',
    description: 'Как клиника организовала регулярный трансфер онкологических пациентов из регионов на лечение в московские центры.',
    keywords: 'кейс перевозка онкопациентов, трансфер пациентов Москва, медтрансфер онкология',
    readingTime: 10,
  },
  {
    slug: 'stoimost-medicinskogo-transfera-mezhgorod-obzor-cen',
    segment: 'medicinskij-transfer',
    format: 'price-review',
    title: 'Стоимость медицинского трансфера межгород: обзор цен',
    description: 'Актуальные цены на медицинский трансфер между городами. Факторы ценообразования, сравнение тарифов, рекомендации.',
    keywords: 'стоимость медицинский трансфер, цены перевозка пациент, тарифы медтрансфер',
    readingTime: 11,
  },
  {
    slug: 'kak-organizovat-perevozku-medpersonala-mezhdu-klinikami',
    segment: 'medicinskij-transfer',
    format: 'guide',
    title: 'Как организовать перевозку медперсонала между клиниками',
    description: 'Руководство по организации трансфера врачей и медсестёр между клиниками и филиалами. Графики, маршруты, оптимизация.',
    keywords: 'перевозка медперсонала, трансфер врачей между клиниками, логистика медицинского персонала',
    readingTime: 10,
  },
  {
    slug: 'chek-list-transfera-posle-operacii',
    segment: 'medicinskij-transfer',
    format: 'checklist',
    title: 'Чек-лист трансфера после операции',
    description: 'Что учесть при перевозке пациента после операции. Медицинские противопоказания, оснащение авто, сопровождение.',
    keywords: 'трансфер после операции, перевозка пациент после операции, чек-лист медтрансфер',
    readingTime: 7,
  },
  {
    slug: 'perevozka-biomaterialov-vs-kurerskaya-dostavka',
    segment: 'medicinskij-transfer',
    format: 'comparison',
    title: 'Перевозка биоматериалов vs курьерская доставка',
    description: 'Сравнение специализированного трансфера и курьерской доставки биоматериалов. Температурный режим, скорость, надёжность.',
    keywords: 'перевозка биоматериалов, доставка анализов межгород, курьер биоматериалы сравнение',
    readingTime: 9,
  },
  {
    slug: 'kejs-transfer-reabilitacionnyh-pacientov-v-sanatorij',
    segment: 'medicinskij-transfer',
    format: 'case-study',
    title: 'Кейс: трансфер реабилитационных пациентов в санаторий',
    description: 'Как санаторная сеть организовала комфортный трансфер пациентов из 8 городов. Маршруты, расписание, отзывы пациентов.',
    keywords: 'кейс трансфер санаторий, перевозка пациентов реабилитация, трансфер в санаторий',
    readingTime: 10,
  },
  {
    slug: 'skolko-stoit-medicinskij-transfer-po-rossii',
    segment: 'medicinskij-transfer',
    format: 'price-review',
    title: 'Сколько стоит медицинский трансфер по России',
    description: 'Полный обзор цен на медицинский трансфер по России. Тарифы по направлениям, классам авто, типам перевозок.',
    keywords: 'стоимость медицинский трансфер Россия, цена перевозка пациент, медтрансфер тарифы',
    readingTime: 11,
  },

  // ===== Сегмент 5: Доставка грузов (10 статей) =====
  {
    slug: 'kak-organizovat-srochnuyu-dostavku-gruzov-mezhgorod',
    segment: 'dostavka-gruzov',
    format: 'guide',
    title: 'Как организовать срочную доставку грузов межгород',
    description: 'Пошаговое руководство по организации срочной доставки грузов между городами. Выбор транспорта, оформление, страхование.',
    keywords: 'срочная доставка грузов, межгородняя доставка, организация доставки груза',
    readingTime: 12,
  },
  {
    slug: 'chek-list-otpravki-gruza-mezhgorod-taksi',
    segment: 'dostavka-gruzov',
    format: 'checklist',
    title: 'Чек-лист отправки груза межгород такси',
    description: 'Проверочный список для отправки груза междугородним такси. Упаковка, документы, страховка, приёмка.',
    keywords: 'чек-лист отправка груза, доставка груза такси, подготовка груза к отправке',
    readingTime: 7,
  },
  {
    slug: 'dostavka-taksi-vs-transportnye-kompanii-sravnenie',
    segment: 'dostavka-gruzov',
    format: 'comparison',
    title: 'Доставка такси vs транспортные компании: сравнение',
    description: 'Подробное сравнение доставки груза такси и транспортными компаниями. Скорость, стоимость, ограничения по весу и габаритам.',
    keywords: 'доставка такси или ТК, сравнение доставка груза, такси для грузов',
    readingTime: 10,
  },
  {
    slug: 'kejs-dostavka-zapchastej-dlya-zavodskogo-prostoja',
    segment: 'dostavka-gruzov',
    format: 'case-study',
    title: 'Кейс: доставка запчастей для заводского простоя',
    description: 'Как экстренная доставка запчастей такси за 400 км спасла завод от трёхдневного простоя и миллионных убытков.',
    keywords: 'кейс доставка запчастей, срочная доставка завод, экстренная доставка груза',
    readingTime: 9,
  },
  {
    slug: 'stoimost-dostavki-gruzov-mezhgorod-obzor-cen',
    segment: 'dostavka-gruzov',
    format: 'price-review',
    title: 'Стоимость доставки грузов межгород: обзор цен',
    description: 'Актуальные цены на доставку грузов между городами. Тарифы по весу, расстоянию, срочности. Как сэкономить.',
    keywords: 'стоимость доставка груз межгород, цены грузовое такси, тарифы доставка грузов',
    readingTime: 11,
  },
  {
    slug: 'kak-dostavit-dokumenty-mezhdu-gorodami-za-neskolko-chasov',
    segment: 'dostavka-gruzov',
    format: 'guide',
    title: 'Как доставить документы между городами за несколько часов',
    description: 'Руководство по срочной доставке документов межгород. Способы, сроки, стоимость, гарантии сохранности.',
    keywords: 'доставка документов межгород, срочная доставка документов, курьер документы между городами',
    readingTime: 9,
  },
  {
    slug: 'chek-list-priemki-gruza-pri-dostavke-mezhgorod',
    segment: 'dostavka-gruzov',
    format: 'checklist',
    title: 'Чек-лист приёмки груза при доставке межгород',
    description: 'Как правильно принять груз после межгородней доставки. Проверка целостности, документы, претензионный порядок.',
    keywords: 'приёмка груза чек-лист, проверка доставки, приёмка межгородней доставки',
    readingTime: 7,
  },
  {
    slug: 'kurerskaya-dostavka-vs-gruzovoe-taksi-chto-bystree',
    segment: 'dostavka-gruzov',
    format: 'comparison',
    title: 'Курьерская доставка vs грузовое такси: что быстрее',
    description: 'Сравнение курьерской службы и грузового такси для доставки межгород. Сроки, стоимость, ограничения, отслеживание.',
    keywords: 'курьерская доставка или грузовое такси, сравнение доставка межгород, грузовое такси скорость',
    readingTime: 9,
  },
  {
    slug: 'kejs-ezhegodnaya-dostavka-obrazcov-dlya-laboratorii',
    segment: 'dostavka-gruzov',
    format: 'case-study',
    title: 'Кейс: ежедневная доставка образцов для лаборатории',
    description: 'Как лаборатория наладила ежедневную доставку образцов из 5 городов. Температурный режим, графики, контроль качества.',
    keywords: 'кейс доставка образцов, логистика лаборатории, доставка проб межгород',
    readingTime: 10,
  },
  {
    slug: 'tarify-na-srochnuyu-dostavku-kak-sekonomit',
    segment: 'dostavka-gruzov',
    format: 'price-review',
    title: 'Тарифы на срочную доставку: как сэкономить',
    description: 'Обзор тарифов на срочную доставку грузов. Лайфхаки экономии, попутные грузы, оптимизация маршрутов.',
    keywords: 'тарифы срочная доставка, экономия доставка грузов, оптимизация доставки',
    readingTime: 10,
  },
]

/** Все slug для generateStaticParams */
export function getAllArticleParams(): { slug: string }[] {
  return ARTICLES.map(a => ({ slug: a.slug }))
}

/** Найти статью по slug */
export function getArticleEntryBySlug(slug: string): ArticleEntry | undefined {
  return ARTICLES.find(a => a.slug === slug)
}

/** Статьи по сегменту */
export function getArticlesBySegment(segment: string): ArticleEntry[] {
  return ARTICLES.filter(a => a.segment === segment)
}
